- hosts: web-servers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
     - name: file edit
       lineinfile:
         path: /home/ubuntu/kafka_2.12-2.3.0/bin/kafka-server-start.sh
         regexp: '-Xmx1G -Xms1G'
         line:     export KAFKA_HEAP_OPTS="-Xmx512m -Xms512m"
