- hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: update ans upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: install jdk 11
    apt:
      name: default-jdk
      state:  present

  - name: clone kafka repo
    shell: wget http://apachemirror.wuchna.com/kafka/2.3.0/kafka_2.12-2.3.0.tgz

  - name: extracting files
    unarchive:
      src: /home/ubuntu/kafka_2.12-2.3.0.tgz
      dest: /home/ubuntu
      remote_src: yes

- hosts: kafka-zookeepers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
     - name: creating myid file for all the zookeepers
       shell: mkdir /tmp/zookeeper
       file: path=/tmp/zookeeper/myid state=touch
       shell: echo 
